version: '3.3'
services:
    picpay-event-tracking-zookeeper:
        container_name: picpay-event-tracking-zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:
            - data-picpay-event-tracking-zookeper:/var/lib/zookeeper/data
            - data-picpay-event-tracking-zookeper-logs:/var/lib/zookeeper/log
        networks:
            - stack
    picpay-event-tracking-kafka:
        container_name: picpay-event-tracking-kafka
        image: confluentinc/cp-kafka:latest
        depends_on:
            - picpay-event-tracking-zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: picpay-event-tracking-zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://picpay-event-tracking-kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        ports:
            - 9092:9092
        volumes:
            - data-picpay-event-tracking-kafka:/var/lib/kafka/data
        networks:
            - stack
    picpay-event-tracking-command:
        container_name: picpay-event-tracking-command
        image: adrianolaselva/php-74-fpm-rdkafka:1.0.0
        volumes:
            - ./:/app
        environment:
            KAFKA_GROUP_ID: event-tracking-command
            KAFKA_METADATA_BROKER_LIST: picpay-event-tracking-kafka:29092
            KAFKA_ENABLE_AUTO_COMMIT: "false"
            KAFKA_AUTO_OFFSET_RESET: earliest
            KAFKA_EVENT_TRACKING_TOPIC: event-tracking-topic
        depends_on:
          - picpay-event-tracking-kafka
        networks:
            - stack
networks: {stack: {}}
volumes:
    data-picpay-event-tracking-kafka:
    data-picpay-event-tracking-zookeper:
    data-picpay-event-tracking-zookeper-logs:
