version: '3.5'
services:

  php:
    build:
      context: .
      args:
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    image: "poc-enqueue-php:latest"
    container_name: poc-enqueue-php
    volumes:
      - .:/var/www/poc-enqueue
    tty: true

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: poc-enqueue-zookeeper
    ports:
      - "2181:2181"

  kafka-manager:
    image: hlebalbau/kafka-manager
    container_name: poc-enqueue-kafka-manager
    ports:
      - "9000:9000"
    environment:
      APPLICATION_SECRET: letmein
      ZK_HOSTS:  zookeeper:2181

  kafka1:
    image: wurstmeister/kafka:latest
    container_name: poc-enqueue-kafka1
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.11.56.40
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
#    volumes:
#      - /Users/thiagovulcao/docker/compose/kafka/data/docker.sock:/var/run/docker.sock

#  kafka2:
#    image: wurstmeister/kafka:latest
#    container_name: poc-enqueue-kafka2
#    ports:
#      - "9098:9098"
#      - "1100:1100"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME:  10.11.57.2
#      KAFKA_PORT: 9098
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_BROKER_ID: 2
#      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1100"
#      JMX_PORT: 1100
#    volumes:
#      - /Users/thiagovulcao/docker/compose/kafka/data/docker.sock:/var/run/docker.sock
